"""add player model

Revision ID: 039c72447d80
Revises: 3ba90ae90746
Create Date: 2026-08-18 12:16:41.818598

"""
from typing import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '039c72447d80'
down_revision: str | Sequence[str] | None = '3ba90ae90746'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_moderators',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('can_control_player', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    sa.Column('can_manage_all_playlists', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_moderators_id'), 'channel_moderators', ['id'], unique=True)
    op.create_index(op.f('ix_channel_moderators_owner_id'), 'channel_moderators', ['owner_id'], unique=False)
    op.create_index('ix_channel_moderators_owner_user', 'channel_moderators', ['owner_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_channel_moderators_token'), 'channel_moderators', ['token'], unique=True)
    op.create_index(op.f('ix_channel_moderators_updated_at'), 'channel_moderators', ['updated_at'], unique=False)
    op.create_index(op.f('ix_channel_moderators_user_id'), 'channel_moderators', ['user_id'], unique=False)
    op.create_table('moderator_playlist_access',
    sa.Column('moderator_id', sa.UUID(), nullable=False),
    sa.Column('playlist_id', sa.UUID(), nullable=False),
    sa.Column('can_manage_tracks', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    sa.Column('can_manage_settings', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['moderator_id'], ['channel_moderators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderator_playlist_access_id'), 'moderator_playlist_access', ['id'], unique=True)
    op.create_index('ix_moderator_playlist_access_mod_plst', 'moderator_playlist_access', ['moderator_id', 'playlist_id'], unique=True)
    op.create_index(op.f('ix_moderator_playlist_access_moderator_id'), 'moderator_playlist_access', ['moderator_id'], unique=False)
    op.create_index(op.f('ix_moderator_playlist_access_playlist_id'), 'moderator_playlist_access', ['playlist_id'], unique=False)
    op.create_index(op.f('ix_moderator_playlist_access_updated_at'), 'moderator_playlist_access', ['updated_at'], unique=False)
    op.drop_index(op.f('ix_playlist_moderators_id'), table_name='playlist_moderators')
    op.drop_index(op.f('ix_playlist_moderators_playlist_id'), table_name='playlist_moderators')
    op.drop_index(op.f('ix_playlist_moderators_playlist_user'), table_name='playlist_moderators')
    op.drop_index(op.f('ix_playlist_moderators_token'), table_name='playlist_moderators')
    op.drop_index(op.f('ix_playlist_moderators_updated_at'), table_name='playlist_moderators')
    op.drop_index(op.f('ix_playlist_moderators_user_id'), table_name='playlist_moderators')
    op.drop_table('playlist_moderators')
    op.drop_column('playlists', 'show_in_widget')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('show_in_widget', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_table('playlist_moderators',
    sa.Column('playlist_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"can_manage_queue": true, "can_manage_playback": true, "can_manage_settings": false}\'::jsonb'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], name=op.f('playlist_moderators_playlist_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('playlist_moderators_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('playlist_moderators_pkey'))
    )
    op.create_index(op.f('ix_playlist_moderators_user_id'), 'playlist_moderators', ['user_id'], unique=False)
    op.create_index(op.f('ix_playlist_moderators_updated_at'), 'playlist_moderators', ['updated_at'], unique=False)
    op.create_index(op.f('ix_playlist_moderators_token'), 'playlist_moderators', ['token'], unique=True)
    op.create_index(op.f('ix_playlist_moderators_playlist_user'), 'playlist_moderators', ['playlist_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_playlist_moderators_playlist_id'), 'playlist_moderators', ['playlist_id'], unique=False)
    op.create_index(op.f('ix_playlist_moderators_id'), 'playlist_moderators', ['id'], unique=True)
    op.drop_index(op.f('ix_moderator_playlist_access_updated_at'), table_name='moderator_playlist_access')
    op.drop_index(op.f('ix_moderator_playlist_access_playlist_id'), table_name='moderator_playlist_access')
    op.drop_index(op.f('ix_moderator_playlist_access_moderator_id'), table_name='moderator_playlist_access')
    op.drop_index('ix_moderator_playlist_access_mod_plst', table_name='moderator_playlist_access')
    op.drop_index(op.f('ix_moderator_playlist_access_id'), table_name='moderator_playlist_access')
    op.drop_table('moderator_playlist_access')
    op.drop_index(op.f('ix_channel_moderators_user_id'), table_name='channel_moderators')
    op.drop_index(op.f('ix_channel_moderators_updated_at'), table_name='channel_moderators')
    op.drop_index(op.f('ix_channel_moderators_token'), table_name='channel_moderators')
    op.drop_index('ix_channel_moderators_owner_user', table_name='channel_moderators')
    op.drop_index(op.f('ix_channel_moderators_owner_id'), table_name='channel_moderators')
    op.drop_index(op.f('ix_channel_moderators_id'), table_name='channel_moderators')
    op.drop_table('channel_moderators')
    # ### end Alembic commands ###
