"""init_db

Revision ID: 289f5f0b2158
Revises:
Create Date: 2026-06-03 08:35:25.791261

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "289f5f0b2158"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("yt_video_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("views", sa.Integer(), nullable=False),
        sa.Column("likes", sa.Integer(), nullable=False),
        sa.Column("priority", sa.String(), nullable=False),
        sa.Column("requester_id", sa.String(), nullable=False),
        sa.Column("requester_nickname", sa.String(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("owner_platform_id", sa.String(), nullable=False),
        sa.Column("from_owner", sa.Boolean(), nullable=False),
        sa.Column("source", sa.Enum("TWITCH", "DA", "YOUTUBE", "GOOGLE", "WEB", name="platform"), nullable=False),
        sa.Column("extra_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_id"),
    )
    op.create_index(op.f("ix_orders_id"), "orders", ["id"], unique=True)
    op.create_index(op.f("ix_orders_updated_at"), "orders", ["updated_at"], unique=False)
    op.create_table(
        "playlists",
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("owner_nickname", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("is_favorite", sa.Boolean(), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("allow_sources", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("is_allow_external_requests", sa.Boolean(), nullable=False),
        sa.Column("now_playing", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_playlists_id"), "playlists", ["id"], unique=True)
    op.create_index(op.f("ix_playlists_updated_at"), "playlists", ["updated_at"], unique=False)
    op.create_table(
        "users",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("email_confirmed", sa.Boolean(), nullable=False),
        sa.Column("avatar_url", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("vip_expires_at", sa.DateTime(), nullable=True),
        sa.Column("social_links", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("last_login", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=True)
    op.create_index(op.f("ix_users_updated_at"), "users", ["updated_at"], unique=False)
    op.create_table(
        "linked_accounts",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("platform", sa.Enum("TWITCH", "DA", "YOUTUBE", "GOOGLE", "WEB", name="platform"), nullable=False),
        sa.Column("platform_user_email", sa.String(), nullable=False),
        sa.Column("platform_user_id", sa.String(), nullable=False),
        sa.Column("platform_username", sa.String(), nullable=False),
        sa.Column("platform_avatar_url", sa.String(), nullable=False),
        sa.Column("bot_connection", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_linked_accounts_id"), "linked_accounts", ["id"], unique=True)
    op.create_index(op.f("ix_linked_accounts_updated_at"), "linked_accounts", ["updated_at"], unique=False)
    op.create_table(
        "order_playlist_status",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("playlist_id", sa.UUID(), nullable=False),
        sa.Column(
            "status", sa.Enum("in playlist", "removed", "listened", "skipped", "reported", native_enum=False), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["playlists.id"],
        ),
        sa.PrimaryKeyConstraint("order_id", "playlist_id"),
    )
    op.create_index(op.f("ix_order_playlist_status_updated_at"), "order_playlist_status", ["updated_at"], unique=False)
    op.create_table(
        "settings",
        sa.Column("playlist_id", sa.UUID(), nullable=False),
        sa.Column("max_playlist_size", sa.Integer(), nullable=False),
        sa.Column("mode", sa.Enum("flow", "static", native_enum=False), nullable=False),
        sa.Column("repeat_mode", sa.Enum("all", "once", "none", native_enum=False), nullable=False),
        sa.Column("sort_settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cost_mode", sa.Enum("add", "max", native_enum=False), nullable=False),
        sa.Column("track_black_list", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["playlist_id"], ["playlists.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_settings_id"), "settings", ["id"], unique=True)
    op.create_index(op.f("ix_settings_playlist_id"), "settings", ["playlist_id"], unique=False)
    op.create_index(op.f("ix_settings_updated_at"), "settings", ["updated_at"], unique=False)
    op.create_table(
        "block_list",
        sa.Column("settings_id", sa.UUID(), nullable=False),
        sa.Column("trigger_type", sa.Enum("USER_ID", "USER_NAME", name="blocktrigger"), nullable=False),
        sa.Column("trigger_value", sa.String(length=255), nullable=False),
        sa.Column("platform", sa.Enum("TWITCH", "DA", "YOUTUBE", "GOOGLE", "WEB", name="platform"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["settings_id"], ["settings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_block_list_id"), "block_list", ["id"], unique=True)
    op.create_index(op.f("ix_block_list_updated_at"), "block_list", ["updated_at"], unique=False)
    op.create_table(
        "chat_rules",
        sa.Column("settings_id", sa.UUID(), nullable=False),
        sa.Column("platform", sa.Enum("TWITCH", "YOUTUBE", name="chatplatform"), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("content_settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("overrive_order", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["settings_id"], ["settings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_rules_id"), "chat_rules", ["id"], unique=True)
    op.create_index("ix_chat_rules_unique_trigger", "chat_rules", ["settings_id", "platform", "key"], unique=True)
    op.create_index(op.f("ix_chat_rules_updated_at"), "chat_rules", ["updated_at"], unique=False)
    op.create_table(
        "content_settings",
        sa.Column("settings_id", sa.UUID(), nullable=False),
        sa.Column(
            "platform", sa.Enum("TWITCH", "YOUTUBE", "GOOGLE", "WEB", "DA", "GENERAL", name="_all_platforms"), nullable=False
        ),
        sa.Column("min_views", sa.Integer(), nullable=False),
        sa.Column("min_likes", sa.Integer(), nullable=False),
        sa.Column("max_duration", sa.Integer(), nullable=False),
        sa.Column("track_cooldown", sa.Integer(), nullable=False),
        sa.Column("user_cooldown", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["settings_id"], ["settings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_content_settings_id"), "content_settings", ["id"], unique=True)
    op.create_index(op.f("ix_content_settings_updated_at"), "content_settings", ["updated_at"], unique=False)
    op.create_table(
        "donation_rules",
        sa.Column("settings_id", sa.UUID(), nullable=False),
        sa.Column("platform", sa.Enum("GENERAL", "DA", name="db_donationplatform"), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("content_settings", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["settings_id"], ["settings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_donation_rules_id"), "donation_rules", ["id"], unique=True)
    op.create_index(
        "ix_donation_rules_unique_trigger", "donation_rules", ["settings_id", "platform", "currency", "amount"], unique=True
    )
    op.create_index(op.f("ix_donation_rules_updated_at"), "donation_rules", ["updated_at"], unique=False)
    op.create_table(
        "token_vault",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("linked_account_id", sa.UUID(), nullable=False),
        sa.Column("platform", postgresql.ENUM("TWITCH", "DA", "YOUTUBE", "GOOGLE", "WEB", name="platform"), nullable=False),
        sa.Column("platform_user_id", sa.String(), nullable=False),
        sa.Column("access_token", sa.String(), nullable=False),
        sa.Column("refresh_token", sa.String(), nullable=False),
        sa.Column("token_type", sa.String(), nullable=False),
        sa.Column("expires_at", sa.Integer(), nullable=False),
        sa.Column("last_update", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["linked_account_id"], ["linked_accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_token_vault_id"), "token_vault", ["id"], unique=True)
    op.create_index(op.f("ix_token_vault_updated_at"), "token_vault", ["updated_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_token_vault_updated_at"), table_name="token_vault")
    op.drop_index(op.f("ix_token_vault_id"), table_name="token_vault")
    op.drop_table("token_vault")
    op.drop_index(op.f("ix_donation_rules_updated_at"), table_name="donation_rules")
    op.drop_index("ix_donation_rules_unique_trigger", table_name="donation_rules")
    op.drop_index(op.f("ix_donation_rules_id"), table_name="donation_rules")
    op.drop_table("donation_rules")
    op.drop_index(op.f("ix_content_settings_updated_at"), table_name="content_settings")
    op.drop_index(op.f("ix_content_settings_id"), table_name="content_settings")
    op.drop_table("content_settings")
    op.drop_index(op.f("ix_chat_rules_updated_at"), table_name="chat_rules")
    op.drop_index("ix_chat_rules_unique_trigger", table_name="chat_rules")
    op.drop_index(op.f("ix_chat_rules_id"), table_name="chat_rules")
    op.drop_table("chat_rules")
    op.drop_index(op.f("ix_block_list_updated_at"), table_name="block_list")
    op.drop_index(op.f("ix_block_list_id"), table_name="block_list")
    op.drop_table("block_list")
    op.drop_index(op.f("ix_settings_updated_at"), table_name="settings")
    op.drop_index(op.f("ix_settings_playlist_id"), table_name="settings")
    op.drop_index(op.f("ix_settings_id"), table_name="settings")
    op.drop_table("settings")
    op.drop_index(op.f("ix_order_playlist_status_updated_at"), table_name="order_playlist_status")
    op.drop_table("order_playlist_status")
    op.drop_index(op.f("ix_linked_accounts_updated_at"), table_name="linked_accounts")
    op.drop_index(op.f("ix_linked_accounts_id"), table_name="linked_accounts")
    op.drop_table("linked_accounts")
    op.drop_index(op.f("ix_users_updated_at"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_playlists_updated_at"), table_name="playlists")
    op.drop_index(op.f("ix_playlists_id"), table_name="playlists")
    op.drop_table("playlists")
    op.drop_index(op.f("ix_orders_updated_at"), table_name="orders")
    op.drop_index(op.f("ix_orders_id"), table_name="orders")
    op.drop_table("orders")
    # ### end Alembic commands ###
