"""add note to order

Revision ID: 3ba90ae90746
Revises: 560320fb1f59
Create Date: 2026-08-16 09:20:11.238016

"""
from typing import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3ba90ae90746'
down_revision: str | Sequence[str] | None = '560320fb1f59'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_playlist_status', sa.Column('note', sa.String(length=500), nullable=True))
    op.add_column('order_playlist_status', sa.Column('is_note_public', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_playlist_status', 'is_note_public')
    op.drop_column('order_playlist_status', 'note')
    # ### end Alembic commands ###
