"""add_playlist_moderators_table

Revision ID: 3cb95d13bf5a
Revises: f9a8b7c6d5e4
Create Date: 2026-08-08 12:37:43.120047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3cb95d13bf5a'
down_revision: Union[str, Sequence[str], None] = 'f9a8b7c6d5e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist_moderators',
    sa.Column('playlist_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('MODERATOR', 'EDITOR', 'CO_AUTHOR', name='moderatorrole', native_enum=False), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default='{"can_manage_queue": true, "can_manage_playback": true, "can_manage_settings": false}', nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playlist_moderators_id'), 'playlist_moderators', ['id'], unique=True)
    op.create_index(op.f('ix_playlist_moderators_playlist_id'), 'playlist_moderators', ['playlist_id'], unique=False)
    op.create_index('ix_playlist_moderators_playlist_user', 'playlist_moderators', ['playlist_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_playlist_moderators_token'), 'playlist_moderators', ['token'], unique=True)
    op.create_index(op.f('ix_playlist_moderators_updated_at'), 'playlist_moderators', ['updated_at'], unique=False)
    op.create_index(op.f('ix_playlist_moderators_user_id'), 'playlist_moderators', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playlist_moderators_user_id'), table_name='playlist_moderators')
    op.drop_index(op.f('ix_playlist_moderators_updated_at'), table_name='playlist_moderators')
    op.drop_index(op.f('ix_playlist_moderators_token'), table_name='playlist_moderators')
    op.drop_index('ix_playlist_moderators_playlist_user', table_name='playlist_moderators')
    op.drop_index(op.f('ix_playlist_moderators_playlist_id'), table_name='playlist_moderators')
    op.drop_index(op.f('ix_playlist_moderators_id'), table_name='playlist_moderators')
    op.drop_table('playlist_moderators')
    # ### end Alembic commands ###

