"""change subscriptions

Revision ID: 52f19ba2749c
Revises: bcdc6575f2cb
Create Date: 2026-07-13 17:21:59.571471

"""

from typing import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "52f19ba2749c"
down_revision: str | Sequence[str] | None = "bcdc6575f2cb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscriptions",
        sa.Column(
            "settings", postgresql.JSONB(astext_type=sa.Text()), server_default='{"allowed_event_types": []}', nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscriptions", "settings")
    # ### end Alembic commands ###
