"""add playback history

Revision ID: 560320fb1f59
Revises: cb84dae00391
Create Date: 2026-08-11 11:08:24.586338

"""
from typing import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '560320fb1f59'
down_revision: str | Sequence[str] | None = 'cb84dae00391'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playback_history',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('playlist_id', sa.UUID(), nullable=False),
    sa.Column('played_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'order_id', name='uq_playback_history_user_order')
    )
    op.create_index(op.f('ix_playback_history_id'), 'playback_history', ['id'], unique=True)
    op.create_index(op.f('ix_playback_history_order_id'), 'playback_history', ['order_id'], unique=False)
    op.create_index(op.f('ix_playback_history_playlist_id'), 'playback_history', ['playlist_id'], unique=False)
    op.create_index(op.f('ix_playback_history_updated_at'), 'playback_history', ['updated_at'], unique=False)
    op.create_index(op.f('ix_playback_history_user_id'), 'playback_history', ['user_id'], unique=False)
    op.create_index('ix_playback_history_user_played', 'playback_history', ['user_id', 'played_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_playback_history_user_played', table_name='playback_history')
    op.drop_index(op.f('ix_playback_history_user_id'), table_name='playback_history')
    op.drop_index(op.f('ix_playback_history_updated_at'), table_name='playback_history')
    op.drop_index(op.f('ix_playback_history_playlist_id'), table_name='playback_history')
    op.drop_index(op.f('ix_playback_history_order_id'), table_name='playback_history')
    op.drop_index(op.f('ix_playback_history_id'), table_name='playback_history')
    op.drop_table('playback_history')
    # ### end Alembic commands ###
