"""add stats filters

Revision ID: 5877b17e59cb
Revises: 7dcdde83b2a2
Create Date: 2026-08-04 20:19:50.352345

"""

from typing import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5877b17e59cb"
down_revision: str | Sequence[str] | None = "7dcdde83b2a2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("stats_visibility", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "stats_visibility")
    # ### end Alembic commands ###
