"""add notifications

Revision ID: 59b1f3dc7958
Revises: e6c9f7027511
Create Date: 2026-07-11 18:55:28.056586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59b1f3dc7958'
down_revision: Union[str, Sequence[str], None] = 'e6c9f7027511'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Таблица событий (Массовые уведомления)
    op.create_table('notification_events',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('target_id', sa.Uuid(), nullable=False),
        sa.Column('target_type', sa.String(), nullable=False),
        sa.Column('event_type', sa.Enum('SYSTEM', 'LIKE', 'NEW_FOLLOWER', name='notificationtype'), nullable=False),
        sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # Поиск событий по подпискам + сортировка по дате
    op.create_index('idx_events_lookup', 'notification_events', ['target_type', 'target_id', 'created_at'], unique=False)

    # 2. Таблица личных уведомлений (Direct)
    op.create_table('direct_notifications',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('notification_type', sa.Enum('SYSTEM', 'LIKE', 'NEW_FOLLOWER', name='notificationtype'), nullable=False),
        sa.Column('notification_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    # Сортировка ленты юзера по дате
    op.create_index('idx_notifications_user_created', 'direct_notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_direct_notifications_updated_at'), 'direct_notifications', ['updated_at'], unique=False)
    # Частичный индекс для быстрого unread_count()
    op.create_index('ix_direct_notifications_user_unread', 'direct_notifications', ['user_id'], unique=False, postgresql_where=sa.text('is_read = false'))

    # 3. Таблица настроек (JSONB)
    op.create_table('notification_settings',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
        sa.Column('last_notification_read_ts', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id') # Этого достаточно, индекс по user_id создастся сам
    )
    op.create_index(op.f('ix_notification_settings_updated_at'), 'notification_settings', ['updated_at'], unique=False)

    # 4. Таблица подписок
    op.create_table('subscriptions',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('target_id', sa.Uuid(), nullable=False),
        sa.Column('target_type', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    # Ускоряет JOIN с событиями по таргету
    op.create_index('idx_subscriptions_target', 'subscriptions', ['target_type', 'target_id'], unique=False)
    # Уникальность подписки юзера на конкретную сущность
    op.create_index('uq_user_sub', 'subscriptions', ['user_id', 'target_type', 'target_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Удаляем индексы и таблицу подписок
    op.drop_index('uq_user_sub', table_name='subscriptions')
    op.drop_index('idx_subscriptions_target', table_name='subscriptions')
    op.drop_table('subscriptions')
    
    # 2. Удаляем индексы и таблицу настроек
    op.drop_index(op.f('ix_notification_settings_updated_at'), table_name='notification_settings')
    op.drop_table('notification_settings')
    
    # 3. Удаляем индексы и таблицу личных уведомлений
    op.drop_index('ix_direct_notifications_user_unread', table_name='direct_notifications', postgresql_where=sa.text('is_read = false'))
    op.drop_index(op.f('ix_direct_notifications_updated_at'), table_name='direct_notifications')
    op.drop_index('idx_notifications_user_created', table_name='direct_notifications')
    op.drop_table('direct_notifications')
    
    # 4. Удаляем индексы и таблицу событий
    op.drop_index('idx_events_lookup', table_name='notification_events')
    op.drop_table('notification_events')
    
    # ПРИМЕЧАНИЕ: Если тип Enum 'notificationtype' создавался через Alembic глобально,
    # и больше нигде не используется, Postgres удалит его автоматически вместе с таблицами.
    # ### end Alembic commands ###
