"""types

Revision ID: 5ab9eb59af00
Revises: 52f19ba2749c
Create Date: 2026-07-13 17:48:07.453024

"""

from typing import Sequence

# revision identifiers, used by Alembic.
revision: str = "5ab9eb59af00"
down_revision: str | Sequence[str] | None = "52f19ba2749c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
