"""add show_in_widget

Revision ID: 5fd2683ce4e2
Revises: 039387e0f804
Create Date: 2026-06-29 20:00:10.934754

"""

from typing import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5fd2683ce4e2"
down_revision: str | Sequence[str] | None = "039387e0f804"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("playlists", sa.Column("show_in_widget", sa.Boolean(), nullable=False, server_default="false"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("playlists", "show_in_widget")
    # ### end Alembic commands ###
