"""remove shuffle add back_ids

Revision ID: 6471fcd4bc08
Revises: b8a22507d4dd
Create Date: 2026-07-26 12:59:39.156347

"""

from typing import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6471fcd4bc08"
down_revision: str | Sequence[str] | None = "b8a22507d4dd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "playlists", sa.Column("background_track_ids", postgresql.ARRAY(sa.String()), server_default="{}", nullable=False)
    )
    op.alter_column("playlists", "background_track_ids", server_default=None)
    op.drop_column("playlists", "shuffle")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("playlists", sa.Column("shuffle", sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column("playlists", "background_track_ids")
    # ### end Alembic commands ###
