"""twitch_admin_tokens

Revision ID: 7dcdde83b2a2
Revises: efad6c67e7dc
Create Date: 2026-08-03 15:43:53.008384

"""

from typing import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7dcdde83b2a2"
down_revision: str | Sequence[str] | None = "efad6c67e7dc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "twitch_admin_tokens",
        sa.Column("twitch_user_id", sa.String(length=255), nullable=True),
        sa.Column("twitch_username", sa.String(length=255), nullable=True),
        sa.Column("twitch_email", sa.String(length=255), nullable=True),
        sa.Column("access_token", sa.String(length=1024), nullable=False),
        sa.Column("refresh_token", sa.String(length=1024), nullable=True),
        sa.Column("token_type", sa.String(length=50), nullable=False),
        sa.Column("expires_in", sa.Integer(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_twitch_admin_tokens_id"), "twitch_admin_tokens", ["id"], unique=True)
    op.create_index(op.f("ix_twitch_admin_tokens_twitch_user_id"), "twitch_admin_tokens", ["twitch_user_id"], unique=False)
    op.create_index(op.f("ix_twitch_admin_tokens_updated_at"), "twitch_admin_tokens", ["updated_at"], unique=False)
    op.create_index(op.f("ix_feature_flags_key"), "feature_flags", ["key"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_feature_flags_key"), table_name="feature_flags")
    op.drop_index(op.f("ix_twitch_admin_tokens_updated_at"), table_name="twitch_admin_tokens")
    op.drop_index(op.f("ix_twitch_admin_tokens_twitch_user_id"), table_name="twitch_admin_tokens")
    op.drop_index(op.f("ix_twitch_admin_tokens_id"), table_name="twitch_admin_tokens")
    op.drop_table("twitch_admin_tokens")
    # ### end Alembic commands ###
