"""add bot settings and is dead for link

Revision ID: 8478f9572bec
Revises: 8d8533322bfe
Create Date: 2026-06-13 20:49:43.973446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8478f9572bec'
down_revision: Union[str, Sequence[str], None] = '8d8533322bfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linked_accounts', sa.Column('bot_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('linked_accounts', sa.Column('is_dead', sa.Boolean(), nullable=False, default=False, server_default="false"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('linked_accounts', 'is_dead')
    op.drop_column('linked_accounts', 'bot_settings')
    # ### end Alembic commands ###
