"""remove native enum

Revision ID: 85c15b86164b
Revises: 8478f9572bec
Create Date: 2026-06-14 13:07:30.571151

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "85c15b86164b"
down_revision: Union[str, Sequence[str], None] = "8478f9572bec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "block_list",
        "trigger_type",
        existing_type=postgresql.ENUM("USER_ID", "USER_NAME", name="blocktrigger"),
        type_=sa.Enum("USER_ID", "USER_NAME", name="blocktrigger", native_enum=False),
        existing_nullable=False,
    )
    op.alter_column(
        "block_list",
        "platform",
        existing_type=postgresql.ENUM("TWITCH", "YOUTUBE", "DA", "WEB", "DONATEX", name="blocklistscope"),
        type_=sa.Enum("TWITCH", "YOUTUBE", "DA", "WEB", "DONATEX", name="blocklistscope", native_enum=False),
        existing_nullable=False,
    )
    op.alter_column(
        "chat_rules",
        "platform",
        existing_type=postgresql.ENUM("TWITCH", "YOUTUBE", name="chatrulescope"),
        type_=sa.Enum("TWITCH", "YOUTUBE", name="chatrulescope", native_enum=False),
        existing_nullable=False,
    )
    op.alter_column(
        "content_settings",
        "platform",
        existing_type=postgresql.ENUM("TWITCH", "YOUTUBE", "WEB", "DA", "DONATEX", "GENERAL", name="contentsettingscope"),
        type_=sa.Enum("TWITCH", "YOUTUBE", "WEB", "DA", "DONATEX", "GENERAL", name="contentsettingscope", native_enum=False),
        existing_nullable=False,
    )
    op.alter_column(
        "donation_rules",
        "platform",
        existing_type=postgresql.ENUM("DA", "DONATEX", "GENERAL", name="donationrulescope"),
        type_=sa.Enum("DA", "DONATEX", "GENERAL", name="donationrulescope", native_enum=False),
        existing_nullable=False,
    )
    op.alter_column(
        "linked_accounts",
        "platform",
        existing_type=postgresql.ENUM("TWITCH", "YOUTUBE", "GOOGLE", "DA", "DONATEX", name="integrationplatform"),
        type_=sa.Enum("TWITCH", "YOUTUBE", "GOOGLE", "DA", "DONATEX", name="integrationplatform", native_enum=False),
        existing_nullable=False,
    )
    op.alter_column(
        "orders",
        "source",
        existing_type=postgresql.ENUM("TWITCH", "DA", "YOUTUBE", "GOOGLE", "WEB", name="platform"),
        type_=sa.Enum("TWITCH", "YOUTUBE", "GOOGLE", "DA", "WEB", "DONATEX", name="platform", native_enum=False),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "source",
        existing_type=sa.Enum("TWITCH", "YOUTUBE", "GOOGLE", "DA", "WEB", "DONATEX", name="platform", native_enum=False),
        type_=postgresql.ENUM("TWITCH", "DA", "YOUTUBE", "GOOGLE", "WEB", name="platform"),
        existing_nullable=False,
    )
    op.alter_column(
        "linked_accounts",
        "platform",
        existing_type=sa.Enum("TWITCH", "YOUTUBE", "GOOGLE", "DA", "DONATEX", name="integrationplatform", native_enum=False),
        type_=postgresql.ENUM("TWITCH", "YOUTUBE", "GOOGLE", "DA", "DONATEX", name="integrationplatform"),
        existing_nullable=False,
    )
    op.alter_column(
        "donation_rules",
        "platform",
        existing_type=sa.Enum("DA", "DONATEX", "GENERAL", name="donationrulescope", native_enum=False),
        type_=postgresql.ENUM("DA", "DONATEX", "GENERAL", name="donationrulescope"),
        existing_nullable=False,
    )
    op.alter_column(
        "content_settings",
        "platform",
        existing_type=sa.Enum(
            "TWITCH", "YOUTUBE", "WEB", "DA", "DONATEX", "GENERAL", name="contentsettingscope", native_enum=False
        ),
        type_=postgresql.ENUM("TWITCH", "YOUTUBE", "WEB", "DA", "DONATEX", "GENERAL", name="contentsettingscope"),
        existing_nullable=False,
    )
    op.alter_column(
        "chat_rules",
        "platform",
        existing_type=sa.Enum("TWITCH", "YOUTUBE", name="chatrulescope", native_enum=False),
        type_=postgresql.ENUM("TWITCH", "YOUTUBE", name="chatrulescope"),
        existing_nullable=False,
    )
    op.alter_column(
        "block_list",
        "platform",
        existing_type=sa.Enum("TWITCH", "YOUTUBE", "DA", "WEB", "DONATEX", name="blocklistscope", native_enum=False),
        type_=postgresql.ENUM("TWITCH", "YOUTUBE", "DA", "WEB", "DONATEX", name="blocklistscope"),
        existing_nullable=False,
    )
    op.alter_column(
        "block_list",
        "trigger_type",
        existing_type=sa.Enum("USER_ID", "USER_NAME", name="blocktrigger", native_enum=False),
        type_=postgresql.ENUM("USER_ID", "USER_NAME", name="blocktrigger"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
