"""auth rebuid

Revision ID: 8d8533322bfe
Revises: dad794a50fdd
Create Date: 2026-06-13 12:19:56.055651

"""

from typing import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d8533322bfe"
down_revision: str | Sequence[str] | None = "dad794a50fdd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


import sqlalchemy as sa

# Обязательно импортируем dialect-специфичный ENUM для Postgres
from sqlalchemy.dialects import postgresql

from alembic import op


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Создаем новые типы ENUM в базе данных
    postgresql.ENUM("TWITCH", "YOUTUBE", "DA", "WEB", "DONATEX", name="blocklistscope").create(op.get_bind())
    postgresql.ENUM("TWITCH", "YOUTUBE", name="chatrulescope").create(op.get_bind())
    postgresql.ENUM("TWITCH", "YOUTUBE", "WEB", "DA", "DONATEX", "GENERAL", name="contentsettingscope").create(op.get_bind())
    postgresql.ENUM("DA", "DONATEX", "GENERAL", name="donationrulescope").create(op.get_bind())
    postgresql.ENUM("TWITCH", "YOUTUBE", "GOOGLE", "DA", "DONATEX", name="integrationplatform").create(op.get_bind())

    # 2. Изменяем типы колонок (код сгенерированный Alembic)
    op.alter_column(
        "block_list",
        "platform",
        existing_type=postgresql.ENUM("TWITCH", "DA", "YOUTUBE", "GOOGLE", "WEB", name="platform"),
        type_=sa.Enum("TWITCH", "YOUTUBE", "DA", "WEB", "DONATEX", name="blocklistscope"),
        existing_nullable=False,
        postgresql_using="platform::text::blocklistscope",
    )  # Явное приведение типов (каст)

    op.alter_column(
        "chat_rules",
        "platform",
        existing_type=postgresql.ENUM("TWITCH", "YOUTUBE", name="chatplatform"),
        type_=sa.Enum("TWITCH", "YOUTUBE", name="chatrulescope"),
        existing_nullable=False,
        postgresql_using="platform::text::chatrulescope",
    )

    op.alter_column(
        "content_settings",
        "platform",
        existing_type=postgresql.ENUM("TWITCH", "YOUTUBE", "GOOGLE", "WEB", "DA", "GENERAL", name="_all_platforms"),
        type_=sa.Enum("TWITCH", "YOUTUBE", "WEB", "DA", "DONATEX", "GENERAL", name="contentsettingscope"),
        existing_nullable=False,
        postgresql_using="platform::text::contentsettingscope",
    )

    op.alter_column(
        "donation_rules",
        "platform",
        existing_type=postgresql.ENUM("GENERAL", "DA", name="db_donationplatform"),
        type_=sa.Enum("DA", "DONATEX", "GENERAL", name="donationrulescope"),
        existing_nullable=False,
        postgresql_using="platform::text::donationrulescope",
    )

    op.alter_column(
        "linked_accounts",
        "platform",
        existing_type=postgresql.ENUM("TWITCH", "DA", "YOUTUBE", "GOOGLE", "WEB", name="platform"),
        type_=sa.Enum("TWITCH", "YOUTUBE", "GOOGLE", "DA", "DONATEX", name="integrationplatform"),
        existing_nullable=False,
        postgresql_using="platform::text::integrationplatform",
    )

    op.alter_column("linked_accounts", "platform_user_email", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("token_vault", "refresh_token", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("token_vault", "expires_at", existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint(op.f("token_vault_user_id_fkey"), "token_vault", type_="foreignkey")
    op.drop_column("token_vault", "platform")
    op.drop_column("token_vault", "platform_user_id")
    op.drop_column("token_vault", "user_id")

    # 3. Удаляем старые, больше не используемые типы ENUM из БД
    postgresql.ENUM(name="chatplatform").drop(op.get_bind())
    postgresql.ENUM(name="_all_platforms").drop(op.get_bind())
    postgresql.ENUM(name="db_donationplatform").drop(op.get_bind())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("token_vault", sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False))
    op.add_column("token_vault", sa.Column("platform_user_id", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column(
        "token_vault",
        sa.Column(
            "platform",
            postgresql.ENUM("TWITCH", "DA", "YOUTUBE", "GOOGLE", "WEB", name="platform"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_foreign_key(op.f("token_vault_user_id_fkey"), "token_vault", "users", ["user_id"], ["id"])
    op.alter_column("token_vault", "expires_at", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("token_vault", "refresh_token", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("linked_accounts", "platform_user_email", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "linked_accounts",
        "platform",
        existing_type=sa.Enum("TWITCH", "YOUTUBE", "GOOGLE", "DA", "DONATEX", name="integrationplatform"),
        type_=postgresql.ENUM("TWITCH", "DA", "YOUTUBE", "GOOGLE", "WEB", name="platform"),
        existing_nullable=False,
    )
    op.alter_column(
        "donation_rules",
        "platform",
        existing_type=sa.Enum("DA", "DONATEX", "GENERAL", name="donationrulescope"),
        type_=postgresql.ENUM("GENERAL", "DA", name="db_donationplatform"),
        existing_nullable=False,
    )
    op.alter_column(
        "content_settings",
        "platform",
        existing_type=sa.Enum("TWITCH", "YOUTUBE", "WEB", "DA", "DONATEX", "GENERAL", name="contentsettingscope"),
        type_=postgresql.ENUM("TWITCH", "YOUTUBE", "GOOGLE", "WEB", "DA", "GENERAL", name="_all_platforms"),
        existing_nullable=False,
    )
    op.alter_column(
        "chat_rules",
        "platform",
        existing_type=sa.Enum("TWITCH", "YOUTUBE", name="chatrulescope"),
        type_=postgresql.ENUM("TWITCH", "YOUTUBE", name="chatplatform"),
        existing_nullable=False,
    )
    op.alter_column(
        "block_list",
        "platform",
        existing_type=sa.Enum("TWITCH", "YOUTUBE", "DA", "WEB", "DONATEX", name="blocklistscope"),
        type_=postgresql.ENUM("TWITCH", "DA", "YOUTUBE", "GOOGLE", "WEB", name="platform"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
