"""add author to track

Revision ID: a793ebb2b351
Revises: 039c72447d80
Create Date: 2026-08-19 11:54:23.257714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a793ebb2b351'
down_revision: Union[str, Sequence[str], None] = '039c72447d80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('author', sa.String(length=255), server_default='Unknown', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'author')
    # ### end Alembic commands ###
