"""add roles and bans

Revision ID: b8a22507d4dd
Revises: cf0c734243e4
Create Date: 2026-07-25 15:18:53.180041

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b8a22507d4dd"
down_revision: str | Sequence[str] | None = "cf0c734243e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ban_list",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ban_list_id"), "ban_list", ["id"], unique=True)
    op.create_index(op.f("ix_ban_list_updated_at"), "ban_list", ["updated_at"], unique=False)
    op.create_table(
        "user_roles",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("tier", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id", "user_id"),
    )
    op.create_index("ix_role_id_user_id_unique", "user_roles", ["id", "user_id"], unique=True)

    # 1. Add non-nullable columns with temporary server_default
    op.add_column("users", sa.Column("bio", sa.String(length=500), server_default="", nullable=False))
    op.add_column("users", sa.Column("is_public", sa.Boolean(), server_default=sa.text("true"), nullable=False))

    # 2. Drop temporary server_default values
    op.alter_column("users", "bio", server_default=None)
    op.alter_column("users", "is_public", server_default=None)

    op.drop_column("users", "vip_expires_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("vip_expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column("users", "is_public")
    op.drop_column("users", "bio")
    op.drop_index("ix_role_id_user_id_unique", table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_ban_list_updated_at"), table_name="ban_list")
    op.drop_index(op.f("ix_ban_list_id"), table_name="ban_list")
    op.drop_table("ban_list")
    # ### end Alembic commands ###
