"""add target_name to sub

Revision ID: bc8c5213c30e
Revises: 6471fcd4bc08
Create Date: 2026-07-28 16:31:46.128324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc8c5213c30e'
down_revision: Union[str, Sequence[str], None] = '6471fcd4bc08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # 1. Добавляем временное nullable-поле
    op.add_column('subscriptions', sa.Column('target_name', sa.String(), nullable=True))

    # 2. Обновляем target_name из таблицы playlists
    op.execute(
        """
        UPDATE subscriptions
        SET target_name = playlists.name
        FROM playlists
        WHERE subscriptions.target_id = playlists.id
          AND UPPER(subscriptions.target_type) = 'PLAYLIST';
        """
    )

    # 3. Обновляем target_name из таблицы users
    op.execute(
        """
        UPDATE subscriptions
        SET target_name = users.username
        FROM users
        WHERE subscriptions.target_id = users.id
          AND UPPER(subscriptions.target_type) = 'USER';
        """
    )

    # 4. Делаем поле NOT NULL
    op.alter_column('subscriptions', 'target_name', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'target_name')
    # ### end Alembic commands ###
