"""add notifications

Revision ID: bcdc6575f2cb
Revises: e6c9f7027511
Create Date: 2026-07-12 11:19:51.913318

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bcdc6575f2cb"
down_revision: Union[str, Sequence[str], None] = "e6c9f7027511"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_events",
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("target_type", sa.String(), nullable=False),
        sa.Column(
            "event_type",
            sa.String(),
            nullable=False,
        ),
        sa.Column("event_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_events_lookup", "notification_events", ["target_type", "target_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_notification_events_id"), "notification_events", ["id"], unique=True)
    op.create_table(
        "direct_notifications",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "notification_type",
            sa.String(),
            nullable=False,
        ),
        sa.Column("notification_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_read", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_notifications_user_created", "direct_notifications", ["user_id", "created_at"], unique=False)
    op.create_index(op.f("ix_direct_notifications_id"), "direct_notifications", ["id"], unique=True)
    op.create_index(op.f("ix_direct_notifications_updated_at"), "direct_notifications", ["updated_at"], unique=False)
    op.create_index(
        "ix_direct_notifications_user_unread",
        "direct_notifications",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("is_read = false"),
    )
    op.create_table(
        "notification_settings",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("last_notification_read_ts", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(op.f("ix_notification_settings_id"), "notification_settings", ["id"], unique=True)
    op.create_index(op.f("ix_notification_settings_updated_at"), "notification_settings", ["updated_at"], unique=False)
    op.create_index("ix_notification_settings_user", "notification_settings", ["user_id"], unique=False)

    op.execute(
        "INSERT INTO notification_settings (id, user_id, filters) "
        "SELECT gen_random_uuid(), id, '{}' FROM users "
        "ON CONFLICT (user_id) DO NOTHING"
    )
    
    op.create_table(
        "subscriptions",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column("target_type", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_subscriptions_target", "subscriptions", ["target_type", "target_id"], unique=False)
    op.create_index(op.f("ix_subscriptions_id"), "subscriptions", ["id"], unique=True)
    op.create_index("uq_user_sub", "subscriptions", ["user_id", "target_type", "target_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_user_sub", table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_id"), table_name="subscriptions")
    op.drop_index("idx_subscriptions_target", table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index("ix_notification_settings_user", table_name="notification_settings")
    op.drop_index(op.f("ix_notification_settings_updated_at"), table_name="notification_settings")
    op.drop_index(op.f("ix_notification_settings_id"), table_name="notification_settings")
    op.drop_table("notification_settings")
    op.drop_index(
        "ix_direct_notifications_user_unread",
        table_name="direct_notifications",
        postgresql_where=sa.text("is_read = false"),
    )
    op.drop_index(op.f("ix_direct_notifications_updated_at"), table_name="direct_notifications")
    op.drop_index(op.f("ix_direct_notifications_id"), table_name="direct_notifications")
    op.drop_index("idx_notifications_user_created", table_name="direct_notifications")
    op.drop_table("direct_notifications")
    op.drop_index(op.f("ix_notification_events_id"), table_name="notification_events")
    op.drop_index("idx_events_lookup", table_name="notification_events")
    op.drop_table("notification_events")
    # ### end Alembic commands ###
