"""merge plst and settings

Revision ID: caf85aa4f3c4
Revises: c2086c61f4fa
Create Date: 2026-07-23 10:22:07.995737

"""

from typing import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "caf85aa4f3c4"
down_revision: str | Sequence[str] | None = "c2086c61f4fa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_settings_id"), table_name="settings")
    op.drop_index(op.f("ix_settings_playlist_id"), table_name="settings")
    op.drop_index(op.f("ix_settings_updated_at"), table_name="settings")
    op.drop_table("settings")
    op.drop_column("donation_rules", "slug")

    # 1. Добавляем колонки с временными server_default для заполнения существующих строк
    op.add_column(
        "playlists",
        sa.Column(
            "max_playlist_size",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
    )
    op.add_column(
        "playlists",
        sa.Column(
            "sync_playback_position",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.add_column(
        "playlists",
        sa.Column(
            "mode",
            sa.Enum("flow", "static", "stream", native_enum=False),
            nullable=False,
            server_default=sa.text("'static'"),
        ),
    )
    op.add_column(
        "playlists",
        sa.Column(
            "repeat_mode",
            sa.Enum("all", "once", "none", native_enum=False),
            nullable=False,
            server_default=sa.text("'none'"),
        ),
    )
    op.add_column(
        "playlists",
        sa.Column(
            "shuffle",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.add_column(
        "playlists",
        sa.Column(
            "cost_mode",
            sa.Enum("add", "max", native_enum=False),
            nullable=False,
            server_default=sa.text("'max'"),
        ),
    )
    op.add_column(
        "playlists",
        sa.Column(
            "mode_settings",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    op.add_column(
        "playlists",
        sa.Column(
            "track_black_list",
            postgresql.ARRAY(sa.String()),
            nullable=False,
            server_default=sa.text("'{}'"),
        ),
    )

    # 2. Сбрасываем server_default на уровне базы данных
    NEW_COLUMNS = [
        "max_playlist_size",
        "sync_playback_position",
        "mode",
        "repeat_mode",
        "shuffle",
        "cost_mode",
        "mode_settings",
        "track_black_list",
    ]
    for column_name in NEW_COLUMNS:
        op.alter_column("playlists", column_name, server_default=None)

    op.alter_column(
        "playlists",
        "tags",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        nullable=False,
    )
    op.create_index(op.f("ix_playlists_owner_id"), "playlists", ["owner_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_playlists_owner_id"), table_name="playlists")
    op.alter_column(
        "playlists",
        "tags",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        nullable=True,
    )
    op.drop_column("playlists", "track_black_list")
    op.drop_column("playlists", "mode_settings")
    op.drop_column("playlists", "cost_mode")
    op.drop_column("playlists", "shuffle")
    op.drop_column("playlists", "repeat_mode")
    op.drop_column("playlists", "mode")
    op.drop_column("playlists", "sync_playback_position")
    op.drop_column("playlists", "max_playlist_size")
    op.add_column(
        "donation_rules",
        sa.Column(
            "slug",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_table(
        "settings",
        sa.Column("playlist_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "max_playlist_size",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("mode", sa.VARCHAR(length=6), autoincrement=False, nullable=False),
        sa.Column(
            "repeat_mode",
            sa.VARCHAR(length=4),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "cost_mode",
            sa.VARCHAR(length=3),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "track_black_list",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "sync_playback_position",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "shuffle",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "mode_settings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text(
                '\'{"flow": {"sort_settings_vip": {"date": "desc", "priority": "none", "order_mode": "auto", "manual_order_ids": []}, "background_track_ids": [], "priority_break_point": 0, "sort_settings_regular": {"date": "desc", "priority": "none", "order_mode": "auto", "manual_order_ids": []}, "sort_settings_background": {"date": "desc", "priority": "none", "order_mode": "auto", "manual_order_ids": []}}, "static": {"sort_settings_vip": {"date": "desc", "priority": "none", "order_mode": "auto", "manual_order_ids": []}, "background_track_ids": [], "priority_break_point": 0, "sort_settings_regular": {"date": "desc", "priority": "none", "order_mode": "auto", "manual_order_ids": []}, "sort_settings_background": {"date": "desc", "priority": "none", "order_mode": "auto", "manual_order_ids": []}}, "stream": {"sort_settings_vip": {"date": "desc", "priority": "none", "order_mode": "auto", "manual_order_ids": []}, "background_track_ids": [], "priority_break_point": 0, "sort_settings_regular": {"date": "desc", "priority": "none", "order_mode": "auto", "manual_order_ids": []}, "sort_settings_background": {"date": "desc", "priority": "none", "order_mode": "auto", "manual_order_ids": []}}}\'::jsonb'
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["playlists.id"],
            name=op.f("settings_playlist_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("settings_pkey")),
    )
    op.create_index(
        op.f("ix_settings_updated_at"),
        "settings",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_settings_playlist_id"),
        "settings",
        ["playlist_id"],
        unique=False,
    )
    op.create_index(op.f("ix_settings_id"), "settings", ["id"], unique=True)
    # ### end Alembic commands ###
