"""remove roles

Revision ID: cb84dae00391
Revises: 3cb95d13bf5a
Create Date: 2026-08-10 12:13:37.158732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb84dae00391'
down_revision: Union[str, Sequence[str], None] = '3cb95d13bf5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('block_list', 'platform',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('TWITCH', 'YOUTUBE', 'DA', 'WEB', 'DONATEX', 'DONATEPAY', name='blocklistscope', native_enum=False),
               existing_nullable=False)
    op.alter_column('content_settings', 'platform',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('TWITCH', 'YOUTUBE', 'WEB', 'DA', 'DONATEX', 'DONATEPAY', 'GENERAL', name='contentsettingscope', native_enum=False),
               existing_nullable=False)
    op.alter_column('donation_rules', 'platform',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('DA', 'DONATEX', 'DONATEPAY', 'GENERAL', name='donationrulescope', native_enum=False),
               existing_nullable=False)
    op.alter_column('linked_accounts', 'platform',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('TWITCH', 'YOUTUBE', 'GOOGLE', 'DA', 'DONATEX', 'DONATEPAY', name='integrationplatform', native_enum=False),
               existing_nullable=False)
    op.alter_column('orders', 'source',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('TWITCH', 'YOUTUBE', 'GOOGLE', 'DA', 'WEB', 'DONATEX', 'DONATEPAY', name='platform', native_enum=False),
               existing_nullable=False)
    op.drop_column('playlist_moderators', 'role')
    op.create_index(op.f('ix_user_favorite_playlists_updated_at'), 'user_favorite_playlists', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_favorite_playlists_updated_at'), table_name='user_favorite_playlists')
    op.add_column('playlist_moderators', sa.Column('role', sa.VARCHAR(length=9), autoincrement=False, nullable=False))
    op.alter_column('orders', 'source',
               existing_type=sa.Enum('TWITCH', 'YOUTUBE', 'GOOGLE', 'DA', 'WEB', 'DONATEX', 'DONATEPAY', name='platform', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('linked_accounts', 'platform',
               existing_type=sa.Enum('TWITCH', 'YOUTUBE', 'GOOGLE', 'DA', 'DONATEX', 'DONATEPAY', name='integrationplatform', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('donation_rules', 'platform',
               existing_type=sa.Enum('DA', 'DONATEX', 'DONATEPAY', 'GENERAL', name='donationrulescope', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('content_settings', 'platform',
               existing_type=sa.Enum('TWITCH', 'YOUTUBE', 'WEB', 'DA', 'DONATEX', 'DONATEPAY', 'GENERAL', name='contentsettingscope', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('block_list', 'platform',
               existing_type=sa.Enum('TWITCH', 'YOUTUBE', 'DA', 'WEB', 'DONATEX', 'DONATEPAY', name='blocklistscope', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###
