"""add playlist logs

Revision ID: dad794a50fdd
Revises: 289f5f0b2158
Create Date: 2026-06-05 09:06:24.389092

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dad794a50fdd"
down_revision: Union[str, Sequence[str], None] = "289f5f0b2158"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "playlist_logs",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("playlist_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("event_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["playlist_id"], ["playlists.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_playlist_logs_user_id_created_at",
        "playlist_logs",
        ["playlist_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(op.f("ix_playlist_logs_id"), "playlist_logs", ["id"], unique=True)
    op.drop_constraint(op.f("order_playlist_status_playlist_id_fkey"), "order_playlist_status", type_="foreignkey")
    op.drop_constraint(op.f("order_playlist_status_order_id_fkey"), "order_playlist_status", type_="foreignkey")
    op.create_foreign_key(None, "order_playlist_status", "playlists", ["playlist_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(None, "order_playlist_status", "orders", ["order_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###
    op.execute("""
    CREATE OR REPLACE FUNCTION clean_old_playlist_logs()
    RETURNS TRIGGER AS $$
    BEGIN
        IF random() < 0.01 THEN
            DELETE FROM playlist_logs
            WHERE playlist_id = NEW.playlist_id 
            AND id NOT IN (
                SELECT id 
                FROM playlist_logs 
                WHERE playlist_id = NEW.playlist_id 
                ORDER BY created_at DESC
                LIMIT 1000
            );
        END IF;
        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)
    op.execute("""
    CREATE OR REPLACE TRIGGER trg_clean_playlist_logs
    AFTER INSERT ON playlist_logs
    FOR EACH ROW
    EXECUTE FUNCTION clean_old_playlist_logs();
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "order_playlist_status", type_="foreignkey")
    op.drop_constraint(None, "order_playlist_status", type_="foreignkey")
    op.create_foreign_key(
        op.f("order_playlist_status_order_id_fkey"), "order_playlist_status", "orders", ["order_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("order_playlist_status_playlist_id_fkey"), "order_playlist_status", "playlists", ["playlist_id"], ["id"]
    )

    op.execute("DROP TRIGGER IF EXISTS trg_clean_playlist_logs ON playlist_logs;")
    op.execute("DROP FUNCTION IF EXISTS clean_old_playlist_logs();")
    op.drop_index(op.f("ix_playlist_logs_id"), table_name="playlist_logs")
    op.drop_index("idx_playlist_logs_user_id_created_at", table_name="playlist_logs")
    op.drop_table("playlist_logs")
    # ### end Alembic commands ###
