"""change sort settings to mode settings

Revision ID: e6c9f7027511
Revises: 5fd2683ce4e2
Create Date: 2026-07-02 07:27:16.253751

"""

import json
from typing import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e6c9f7027511"
down_revision: str | Sequence[str] | None = "5fd2683ce4e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("settings", sa.Column("sync_playback_position", sa.Boolean(), server_default="false", nullable=False))
    op.add_column("settings", sa.Column("shuffle", sa.Boolean(), server_default="false", nullable=False))
    op.add_column(
        "settings",
        sa.Column(
            "mode_settings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=json.dumps(
                {
                    "flow": {
                        "priority_break_point": 0,
                        "sort_settings_vip": {"date": "desc", "priority": "none", "order_mode": "auto", "manual_order_ids": []},
                        "sort_settings_regular": {
                            "date": "desc",
                            "priority": "none",
                            "order_mode": "auto",
                            "manual_order_ids": [],
                        },
                        "sort_settings_background": {
                            "date": "desc",
                            "priority": "none",
                            "order_mode": "auto",
                            "manual_order_ids": [],
                        },
                        "background_track_ids": [],
                    },
                    "static": {
                        "priority_break_point": 0,
                        "sort_settings_vip": {"date": "desc", "priority": "none", "order_mode": "auto", "manual_order_ids": []},
                        "sort_settings_regular": {
                            "date": "desc",
                            "priority": "none",
                            "order_mode": "auto",
                            "manual_order_ids": [],
                        },
                        "sort_settings_background": {
                            "date": "desc",
                            "priority": "none",
                            "order_mode": "auto",
                            "manual_order_ids": [],
                        },
                        "background_track_ids": [],
                    },
                    "stream": {
                        "priority_break_point": 0,
                        "sort_settings_vip": {"date": "desc", "priority": "none", "order_mode": "auto", "manual_order_ids": []},
                        "sort_settings_regular": {
                            "date": "desc",
                            "priority": "none",
                            "order_mode": "auto",
                            "manual_order_ids": [],
                        },
                        "sort_settings_background": {
                            "date": "desc",
                            "priority": "none",
                            "order_mode": "auto",
                            "manual_order_ids": [],
                        },
                        "background_track_ids": [],
                    },
                }
            ),
            nullable=False,
        ),
    )
    op.drop_column("settings", "sort_settings")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "settings", sa.Column("sort_settings", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True)
    )
    op.drop_column("settings", "mode_settings")
    op.drop_column("settings", "shuffle")
    op.drop_column("settings", "sync_playback_position")
    # ### end Alembic commands ###
