"""add feature flags

Revision ID: efad6c67e7dc
Revises: bc8c5213c30e
Create Date: 2026-07-30 12:31:25.674780

"""

from typing import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "efad6c67e7dc"
down_revision: str | Sequence[str] | None = "bc8c5213c30e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feature_flags",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("min_tier", sa.Integer(), nullable=False),
        sa.Column("scope", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_feature_flags_id"), "feature_flags", ["id"], unique=True)
    op.create_index(op.f("ix_feature_flags_updated_at"), "feature_flags", ["updated_at"], unique=False)
    op.add_column("user_roles", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.drop_index(op.f("ix_role_id_user_id_unique"), table_name="user_roles")
    op.create_index("ix_user_roles_user_id", "user_roles", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_roles_user_id", table_name="user_roles")
    op.create_index(op.f("ix_role_id_user_id_unique"), "user_roles", ["id", "user_id"], unique=True)
    op.drop_column("user_roles", "is_active")
    op.drop_index(op.f("ix_feature_flags_updated_at"), table_name="feature_flags")
    op.drop_index(op.f("ix_feature_flags_id"), table_name="feature_flags")
    op.drop_table("feature_flags")
    # ### end Alembic commands ###
