volumes:
  postgres_data:
    driver: local

  rabbitmq_data:
    driver: local

  redis_data:
    driver: local

networks:
  default:
    driver: bridge

services:

  rabbitmq:
    image: rabbitmq:4.1.2-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - default
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    networks:
      - default
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30

  database:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U openplaylist_mono_user -d openplaylist_mono" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5438:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  traefik:
    image: traefik:v3.6.7
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=nikitavolov444@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - default

  backend:
    build: ./back-end
    ports:
      - "8000:8000"
    depends_on:
          database:
            condition: service_healthy
          redis:
            condition: service_healthy
          rabbitmq:
            condition: service_healthy
    env_file:
      - ./back-end/.env
    volumes:
      - ./back-end/src:/app/src
    labels:
      - "traefik.enable=true"
      # Направляем все запросы, начинающиеся с /api, на бэкенд
      - "traefik.http.routers.backend.rule=Host(`${PROJECT_DOMAIN:-openplaylist.localhost}`) && PathPrefix(`/api`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.priority=100"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
    networks:
      - default
    healthcheck:
      test: curl --fail http://localhost:8000/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
      
    stop_grace_period: 30s

  task-worker:
    build:
      context: ./back-end
      dockerfile: ./Dockerfile.tasks
    depends_on:
          database:
            condition: service_healthy
          redis:
            condition: service_healthy
          rabbitmq:
            condition: service_healthy
    env_file:
      - ./back-end/.env
    volumes:
      - ./back-end/src:/app/src
    networks:
      - default

  task-schuduler:
    build:
      context: ./back-end
      dockerfile: ./Dockerfile.scheduler
    depends_on:
          database:
            condition: service_healthy
          redis:
            condition: service_healthy
          rabbitmq:
            condition: service_healthy
    env_file:
      - ./back-end/.env
    volumes:
      - ./back-end/src:/app/src
    networks:
      - default

  bot-ttv:
    build:
      context: ./bot_ttv
      dockerfile: ./Dockerfile
    depends_on:
      backend:
        condition: service_healthy
    env_file:
      - ./bot_ttv/.env
    volumes:
      - ./bot_ttv/src:/app/src
      - ./bot_ttv/main.py:/app/main.py
    networks:
      - default

  bot-da:
    build:
      context: ./bot_da
      dockerfile: ./Dockerfile
    depends_on:
      backend:
        condition: service_healthy
    env_file:
      - ./bot_da/.env
    volumes:
      - ./bot_da/src:/app/src
    networks:
      - default

  frontend:
    build:
      context: ./new_ui
      dockerfile: Dockerfile
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${PROJECT_DOMAIN:-openplaylist.localhost}`)"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

    networks:
      - default
