/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViewRouteImport } from './routes/view'
import { Route as TwitchCallbackRouteImport } from './routes/twitch-callback'
import { Route as StatisticRouteImport } from './routes/statistic'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DaCallbackRouteImport } from './routes/da-callback'
import { Route as IndexRouteImport } from './routes/index'

const ViewRoute = ViewRouteImport.update({
  id: '/view',
  path: '/view',
  getParentRoute: () => rootRouteImport,
} as any)
const TwitchCallbackRoute = TwitchCallbackRouteImport.update({
  id: '/twitch-callback',
  path: '/twitch-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticRoute = StatisticRouteImport.update({
  id: '/statistic',
  path: '/statistic',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DaCallbackRoute = DaCallbackRouteImport.update({
  id: '/da-callback',
  path: '/da-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/da-callback': typeof DaCallbackRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/logout': typeof LogoutRoute
  '/settings': typeof SettingsRoute
  '/statistic': typeof StatisticRoute
  '/twitch-callback': typeof TwitchCallbackRoute
  '/view': typeof ViewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/da-callback': typeof DaCallbackRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/logout': typeof LogoutRoute
  '/settings': typeof SettingsRoute
  '/statistic': typeof StatisticRoute
  '/twitch-callback': typeof TwitchCallbackRoute
  '/view': typeof ViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/da-callback': typeof DaCallbackRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/logout': typeof LogoutRoute
  '/settings': typeof SettingsRoute
  '/statistic': typeof StatisticRoute
  '/twitch-callback': typeof TwitchCallbackRoute
  '/view': typeof ViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/da-callback'
    | '/dashboard'
    | '/history'
    | '/logout'
    | '/settings'
    | '/statistic'
    | '/twitch-callback'
    | '/view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/da-callback'
    | '/dashboard'
    | '/history'
    | '/logout'
    | '/settings'
    | '/statistic'
    | '/twitch-callback'
    | '/view'
  id:
    | '__root__'
    | '/'
    | '/da-callback'
    | '/dashboard'
    | '/history'
    | '/logout'
    | '/settings'
    | '/statistic'
    | '/twitch-callback'
    | '/view'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DaCallbackRoute: typeof DaCallbackRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  LogoutRoute: typeof LogoutRoute
  SettingsRoute: typeof SettingsRoute
  StatisticRoute: typeof StatisticRoute
  TwitchCallbackRoute: typeof TwitchCallbackRoute
  ViewRoute: typeof ViewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/view': {
      id: '/view'
      path: '/view'
      fullPath: '/view'
      preLoaderRoute: typeof ViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twitch-callback': {
      id: '/twitch-callback'
      path: '/twitch-callback'
      fullPath: '/twitch-callback'
      preLoaderRoute: typeof TwitchCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistic': {
      id: '/statistic'
      path: '/statistic'
      fullPath: '/statistic'
      preLoaderRoute: typeof StatisticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/da-callback': {
      id: '/da-callback'
      path: '/da-callback'
      fullPath: '/da-callback'
      preLoaderRoute: typeof DaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DaCallbackRoute: DaCallbackRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  LogoutRoute: LogoutRoute,
  SettingsRoute: SettingsRoute,
  StatisticRoute: StatisticRoute,
  TwitchCallbackRoute: TwitchCallbackRoute,
  ViewRoute: ViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
