/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatisticRouteImport } from './routes/statistic'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PolicyRouteImport } from './routes/policy'
import { Route as OauthCallbackRouteImport } from './routes/oauth-callback'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as EmailConfirmRouteImport } from './routes/email-confirm'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SavesIndexRouteImport } from './routes/saves.index'
import { Route as PlaylistsIndexRouteImport } from './routes/playlists.index'
import { Route as PlaylistsPlaylistIdRouteImport } from './routes/playlists.$playlistId'

const StatisticRoute = StatisticRouteImport.update({
  id: '/statistic',
  path: '/statistic',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/policy.lazy').then((d) => d.Route))
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth-callback',
  path: '/oauth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailConfirmRoute = EmailConfirmRouteImport.update({
  id: '/email-confirm',
  path: '/email-confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SavesIndexRoute = SavesIndexRouteImport.update({
  id: '/saves/',
  path: '/saves/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsIndexRoute = PlaylistsIndexRouteImport.update({
  id: '/playlists/',
  path: '/playlists/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsPlaylistIdRoute = PlaylistsPlaylistIdRouteImport.update({
  id: '/playlists/$playlistId',
  path: '/playlists/$playlistId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/email-confirm': typeof EmailConfirmRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/policy': typeof PolicyRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/statistic': typeof StatisticRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/playlists': typeof PlaylistsIndexRoute
  '/saves': typeof SavesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/email-confirm': typeof EmailConfirmRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/policy': typeof PolicyRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/statistic': typeof StatisticRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/playlists': typeof PlaylistsIndexRoute
  '/saves': typeof SavesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/email-confirm': typeof EmailConfirmRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/oauth-callback': typeof OauthCallbackRoute
  '/policy': typeof PolicyRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/statistic': typeof StatisticRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/saves/': typeof SavesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/email-confirm'
    | '/history'
    | '/login'
    | '/logout'
    | '/oauth-callback'
    | '/policy'
    | '/register'
    | '/settings'
    | '/statistic'
    | '/playlists/$playlistId'
    | '/playlists'
    | '/saves'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/email-confirm'
    | '/history'
    | '/login'
    | '/logout'
    | '/oauth-callback'
    | '/policy'
    | '/register'
    | '/settings'
    | '/statistic'
    | '/playlists/$playlistId'
    | '/playlists'
    | '/saves'
  id:
    | '__root__'
    | '/'
    | '/email-confirm'
    | '/history'
    | '/login'
    | '/logout'
    | '/oauth-callback'
    | '/policy'
    | '/register'
    | '/settings'
    | '/statistic'
    | '/playlists/$playlistId'
    | '/playlists/'
    | '/saves/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmailConfirmRoute: typeof EmailConfirmRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  PolicyRoute: typeof PolicyRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  StatisticRoute: typeof StatisticRoute
  PlaylistsPlaylistIdRoute: typeof PlaylistsPlaylistIdRoute
  PlaylistsIndexRoute: typeof PlaylistsIndexRoute
  SavesIndexRoute: typeof SavesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statistic': {
      id: '/statistic'
      path: '/statistic'
      fullPath: '/statistic'
      preLoaderRoute: typeof StatisticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth-callback': {
      id: '/oauth-callback'
      path: '/oauth-callback'
      fullPath: '/oauth-callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-confirm': {
      id: '/email-confirm'
      path: '/email-confirm'
      fullPath: '/email-confirm'
      preLoaderRoute: typeof EmailConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saves/': {
      id: '/saves/'
      path: '/saves'
      fullPath: '/saves'
      preLoaderRoute: typeof SavesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/': {
      id: '/playlists/'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/$playlistId': {
      id: '/playlists/$playlistId'
      path: '/playlists/$playlistId'
      fullPath: '/playlists/$playlistId'
      preLoaderRoute: typeof PlaylistsPlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmailConfirmRoute: EmailConfirmRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  PolicyRoute: PolicyRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  StatisticRoute: StatisticRoute,
  PlaylistsPlaylistIdRoute: PlaylistsPlaylistIdRoute,
  PlaylistsIndexRoute: PlaylistsIndexRoute,
  SavesIndexRoute: SavesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
