FROM python:3.13.7-alpine3.21

WORKDIR /app

# Устанавливаем uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY pyproject.toml uv.lock ./

RUN uv sync --frozen --no-cache --no-dev

COPY . .

WORKDIR /app/src

CMD ["uv", "run", "taskiq", "scheduler","taskiq_broker:scheduler", "tasks.tokens"]