FROM python:3.13.6-alpine3.22

WORKDIR /app

# Устанавливаем uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY pyproject.toml uv.lock ./

RUN uv sync --frozen --no-cache --no-dev

COPY . .

WORKDIR /app

CMD ["uv", "run", "--no-dev", "taskiq", "worker", "taskiq_broker:task_broker", "src.tasks.order", "src.tasks.playlist", "src.tasks.email", "src.tasks.tokens", "src.tasks.playback"]