[project]
name = "auth-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.21.0",
    "cryptography>=45.0.5",
    "pydantic-settings>=2.9.1",
    "pyjwt>=2.10.1",
    "sqlalchemy[asyncio]>=2.0.40",
    "uvicorn>=0.34.2",
    "pydantic[email]>=2.11.3",
    "uuid6>=2024.7.10",
    "python-dotenv>=1.1.0",
    "simple-repo-asyncsqla==2.2.0",
    "faststream[cli,rabbit]>=0.5.48",
    "asyncpg>=0.30.0",
    "pytubefix>=10.3.6",
    "redis>=7.1.0",
    "alembic>=1.17.2",
    "fastapi-events>=0.12.2",
    "python-socketio>=5.16.0",
    "taskiq>=0.12.1",
    "taskiq-redis>=1.2.1",
    "argon2-cffi>=25.1.0",
    "fastapi>=0.136.1",
    "httpx>=0.28.1",
    "google-api-python-client>=2.197.0",
    "isodate>=0.7.2",
    "orjson>=3.11.9",
    "sqladmin[full]>=0.30.0",
]

[dependency-groups]
dev = [
    "factory-boy>=3.3.3",
    "pytest>=9.0.3",
    "pytest-asyncio>=1.3.0",
    "pytest-env>=1.6.0",
    "pytest-mock>=3.15.1",
]


[tool.basedpyright]
enableExperimentalFeatures = true

reportUnknownMemberType = "none"
reportUnusedCallResult = "none"
reportUnknownVariableType = "none"
reportUnknownArgumentType = "none"
reportPrivateLocalImportUsage = "none"
reportExplicitAny = "none"
reportAny = "none"
reportMissingTypeStubs = "none"
